/**
 * Exportable / shareable delegation record.
 *
 * "Here is exactly what I let my agent do today" — as plain text a person can
 * read, and as JSON another system could verify. Both are generated from the
 * same contract + ledger, so the readable version cannot drift from the record.
 */

import { contractSummary, describeMatcher } from './contract'
import type { DelegationContract, LedgerEntry } from './types'

export interface ExportBundle {
  format: 'taskfence.delegation.v1'
  exportedAt: string
  contract: DelegationContract
  activity: LedgerEntry[]
  counts: Record<string, number>
}

export function buildExport(contract: DelegationContract, ledger: LedgerEntry[]): ExportBundle {
  const activity = ledger.filter((e) => e.taskId === contract.taskId)
  const counts = activity.reduce<Record<string, number>>((acc, e) => {
    acc[e.status] = (acc[e.status] ?? 0) + 1
    return acc
  }, {})
  return {
    format: 'taskfence.delegation.v1',
    exportedAt: new Date().toISOString(),
    contract,
    activity,
    counts,
  }
}

const time = (n: number) => new Date(n).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })

export function toPlainLanguage(contract: DelegationContract, ledger: LedgerEntry[]): string {
  const s = contractSummary(contract)
  const activity = ledger.filter((e) => e.taskId === contract.taskId)
  const lines: string[] = []

  lines.push(`TaskFence — what I allowed my agent to do`)
  lines.push(`Task: ${contract.title}`)
  lines.push(`Date: ${new Date(contract.createdAt).toLocaleString()}`)
  lines.push(`Agent: ${contract.agentId}`)
  lines.push('')
  lines.push(`I said:`)
  lines.push(`  "${contract.statement}"`)
  lines.push('')

  lines.push('I allowed:')
  s.allowed.forEach((r) => lines.push(`  - ${r.label} (${describeMatcher(r.match)})`))
  if (!s.allowed.length) lines.push('  - nothing')

  lines.push('')
  lines.push('I ruled out:')
  s.forbidden.forEach((r) => lines.push(`  - ${r.label}`))
  if (!s.forbidden.length) lines.push('  - nothing')

  lines.push('')
  lines.push('I kept the final say on:')
  s.requiresApproval.forEach((r) => lines.push(`  - ${r.label}`))
  if (!s.requiresApproval.length) lines.push('  - nothing')

  const exceptions = s.exceptions
  if (exceptions.length) {
    lines.push('')
    lines.push('One-off permissions I granted during the task:')
    exceptions.forEach((r) =>
      lines.push(`  - ${r.label} — ${r.retiredAt ? 'used once, then expired' : `${r.uses ?? 'unlimited'} use(s) left`}`),
    )
  }

  lines.push('')
  lines.push('What actually happened:')
  activity.forEach((e) => {
    lines.push(`  ${time(e.at)}  [${label(e.status)}] ${e.title}${e.field ? ` — ${e.field}` : ''}`)
    if (e.status !== 'allowed') lines.push(`             ${e.reason}`)
  })
  if (!activity.length) lines.push('  nothing yet')

  lines.push('')
  lines.push('Generated by TaskFence. Every line above is taken from the enforcement log,')
  lines.push('not written after the fact.')

  return lines.join('\n')
}

function label(status: LedgerEntry['status']): string {
  switch (status) {
    case 'allowed':
      return 'done'
    case 'denied':
      return 'blocked'
    case 'awaiting-approval':
      return 'paused'
    case 'approved-with-exception':
      return 'you allowed'
    case 'refused-by-human':
      return 'you refused'
    case 'expired':
      return 'expired'
    default:
      return 'error'
  }
}

export function download(filename: string, contents: string, type = 'text/plain'): void {
  const blob = new Blob([contents], { type })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
